spring.application.name=DiscoveryServer
server.port=8761

#Host de eureka
eureka.instance.hostname=discovery-server

#Ruta donde se registran los microservicios
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka

#Indica que eureka no debe registrarse a si mismo
eureka.client.register-with-eureka=false

#Indica que eureka no puede descargar el registro de los MS
eureka.client.fetch-registry=false

#Habilitamos la autopreservacion
eureka.server.enable-self-preservation=true