spring.application.name=Gateway
server.port=9999

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Gateway Discovery
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=false

# Huespedes
spring.cloud.gateway.server.webmvc.routes[0].id=MS-HUESPEDES
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://MS-HUESPEDES
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/huespedes/**

# Habitaciones
spring.cloud.gateway.server.webmvc.routes[1].id=MS-HABITACIONES
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://MS-HABITACIONES
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/habitaciones/**

# Reservaciones
spring.cloud.gateway.server.webmvc.routes[2].id=MS-RESERVACIONES
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://MS-RESERVACIONES
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/reservaciones/**