spring.application.name=MS-RESERVACIONES

server.port=8024



spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=system
spring.datasource.password=olmos123

spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database=oracle
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true


#hibernmete
#muestra las consultas generadas desde la consola
#configuracion de eureka
eureka.instance.hostname=localhost

eureka.client.service-url.DefaultZone=http://localhost:8761/eureka


